### ISSUE TITLE
segmentation fault since commit bb4b7f100f972206843d8c1b07eab820d653d9e9

### ISSUE THREAD

**Issue by trentasis** [jackburton79/agent#10]
With thinstation 5.4 I have reproduced an error since commit https://github.com/jackburton79/agent/commit/bb4b7f100f972206843d8c1b07eab820d653d9e9

With previous versions was working perfect, last versions working was https://github.com/jackburton79/agent/commit/617049625e0d018f4223582dad2976005f83bb7e

Thanks

**Comment by trentasis** [comment]
debugger result:

Program received signal SIGSEGV, Segmentation fault.
0xf7f6d063 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /usr/lib/libstdc++.so.6

**Comment by jackburton79** [comment]
Might have been fixed in dff3f5c99e003f98352c5aef1619c127622f1be8.
Could you try ?
Thanks!

**Comment by trentasis** [comment]
Works perfect!!
Thanks
