### ISSUE TITLE
Ram value not correctly inventoried & agent version

### ISSUE THREAD

**Issue by trentasis** [jackburton79/agent#12]
Twuo questions

1)
With added support to detect RAM slots is a great tool.
Only one issue, in ocs server inventory result is not the same value detected, for example:

We have a machine with 512 MB RAM, and in memory slots show correctly 512 but in table inventory result show 500MB

2) It will be interesting taht in Inventory.cpp, exactly in 
#define USER_AGENT "OCS-NG_unified_unix_agent_v"

show as agent same string +git number to know version running

#define USER_AGENT "OCS-NG_unified_unix_agent_v git #####"

Thanks

**Comment by jackburton79** [comment]
Hi, I'm working on the RAM issue.
For the agent version, the problem is, that OCSInventory (server) doesn't just accept any version string. After many tries, I managed to have it accept the version string if I pass "OCS-NG_unified_unix_agent_v" as version. I should work with them and ask for a custom version string for my agent.

**Comment by trentasis** [comment]
ok, about ram issue.
ok, about agent version.

thanks

**Comment by trentasis** [comment]
I have searched in code, but I con't find where is the error, do you have an idea?
Thanks

**Comment by trentasis** [comment]
setup54.sh has incorrect permission, required permissions are the same of setup22.sh

Thanks

**Comment by jackburton79** [comment]
I think I've found the problema about wrong reported RAM amount. The agent gets that value from /proc/meminfo (in kb) and divides it by 1024.  It should divide it by 1000 instead. I always get confused on this thing, since I'm pretty old and for me kilobytes are  always 1024 bytes.
