### ISSUE TITLE
port different from 80 can't be used

### ISSUE THREAD

**Issue by jonathan-orsel** [jackburton79/agent#14]
if an URL contain a port, it doesn't works.
for exemple : --server http://\<ocsserver\>:\<ocsport\>/ocsinventory 
it seems the port is hard coded in HTTP/http.h
As workaround I changed the default port in HTTP/http.h

Anyway, Thanks a lot for sharing this "lite" agent, very usefull !

**Comment by jackburton79** [comment]
Should be fixed. Could you try ?

**Comment by jonathan-orsel** [comment]
Yes ! thank you boss!
