### ISSUE TITLE
Thinstation ocsinventory - TAG support

### ISSUE THREAD

**Issue by piozylka** [jackburton79/agent#19]
It seems that thinstation agent doesn't support TAG option which is available at original ocsinventory-agent.
Is there any option to send TAG ??

**Comment by jackburton79** [comment]
Il 23 giu 2017 10:53 AM, "piozylka" <notifications@github.com> ha scritto:

It seems that thinstation agent doesn't support TAG option which is
available at original ocsinventory-agent.
Is there any option to send TAG ??

Hi, at the moment, sending the tag is not supported. Since we dont use it,
I did not implement it. I can look into it, if there's need for It.

**Comment by piozylka** [comment]
It would be great !
Thank you

**Comment by jackburton79** [comment]
Just to clarify: you mean the ability to send the TAG (which you can set from the BIOS) from the client to the ocsinventory server ? or to receive the TAG which you set from the ocsinventory server to the client?

**Comment by piozylka** [comment]
I mean the TAG which u can set in ocsinventory, option -t in original ocsinventory-agent

**Comment by jackburton79** [comment]
I implemented tag sending functionality in c95c798c68fcbd293aa828ca8624bec4e1124cf1.
I briefly tested and it seems to work, but having never used such functionality in ocsinventory, I can't say if it does what you expect.
Could you give it a try ?

**Comment by piozylka** [comment]
how can i implement this version in thinstation ?
thinstation update package is enough for this ?

**Comment by jackburton79** [comment]
Currently the Thinstation package points to an old version, so you'd have to do this manually.
Which version of Thinstation are you using ? Maybe I could upload an already compiled package.

**Comment by piozylka** [comment]
i think im using 5.4 
where can i check version ?

**Comment by jackburton79** [comment]
I think version 5.4 already points to the master of ocsinventory.
The Pkgfile of ocsinventory (in ts/ports/packages/ocsinventory) should be like this:

<pre>
# Description: Thinstation essential package
# URL: http://www.thinstation.org
# Maintainer: Donald A. Cupp Jr. (don cupp jr at ya hoo dot com)

name=ocsinventory
version=git
release=1
source=()

build() {
git clone https://github.com/jackburton79/agent.git
        cd agent
        make
        mkdir -p $PKG/bin
        cp  ocsinventory-agent $PKG/bin/.
}
</pre>
so I think you just need to:
- Enter the chroot environment
- 'cd' into the following directory, starting from the thinstation root: ts/ports/components/ocsinventory
- launch 'pkgmk -u' (it should print some information on screen, while it downloads and builds the new version)
- Rebuild the thinstation image

**Comment by piozylka** [comment]
Done, package nicely updated, image build done.
ocs report is sended but without tag information, tired both manually and via config file.
no changes, when i call ocsinventory-agent --help it doesnt show information about -t option, only:
-h help
-c conf
-s server
Is this correct ?

**Comment by jackburton79** [comment]
Nope, I think it hasn't updated. To be sure, launching the application with the -h switch should show version 1.5.

**Comment by jackburton79** [comment]
Could you Aldo remove any .zip or .Tar.gz or tar.xz file present in the above directory ?

**Comment by jackburton79** [comment]
And the Launcher pkgmk -u again

**Comment by piozylka** [comment]
I was fighting with this all day, here's what I did and my conclusions:
- did a fresh install of Thinstation 5.5.
- updated a package ocsinventory, update confirmed
- checked in Thinstation ocsinventory-agent -h , shows up 1.5 version and oprion -t for tags
- added packege ocsinventory in bulid.conf and builded simple image
- booted from pendrive with builded image, ocsinventory-agent still the same old version.
So maybe I'm doing smthing wrong and package doesn't integrate to image ?
Tried to remove all files tar.gz , tar.xz from /ts/ports/components/ocsinventory and did upgrade
but after this image doesnt integrate package ocsinventory at all.

**Comment by jackburton79** [comment]
I think it happened to me, too. In that case, I think I manually copied the generated binary (which is compressed into a xz executable) to the package directory in the Thinstation tree (if I remember correctly, that would be ts/build/packages/ocsinventory-ng/bin)

**Comment by trentasis** [comment]
Try with

pkgmk -u -d -um
pkgmk -u
pkgmk -uf
pkgmk -u
update package


2017-07-05 21:43 GMT+02:00 Stefano Ceccherini <notifications@github.com>:

**Comment by piozylka** [comment]
@jackburton79 Indeed I had to manually extract and copy to ts/build/packages/ocsinventory-ng/bin
Now it's working but due to [bug](https://github.com/OCSInventory-NG/UnixAgent/issues/59)  I cannot test it.
@trentasis thx for help, I will try this next time.

**Comment by jackburton79** [comment]
In fact didnt work for me either, for an already inventoried machine. Works
if I delete the machine and retry to send the inveentory.

Il 06 lug 2017 1:46 PM, "piozylka" <notifications@github.com> ha scritto:

**Comment by jackburton79** [comment]
I'm closing this, since adding the tag while inventorying a new machine works.

**Comment by piozylka** [comment]
Confirmed, adding new machine works.
Thank u , very much.
