### ISSUE TITLE
Memory inventory broken when retrieved via lshw

### ISSUE THREAD

**Issue by jackburton79** [jackburton79/agent#27]
Memory inventory is broken if retrieved from lshw output.
Depending on the configuration, it will create multiple entries with size = NULL, or no entries at all.

**Comment by jackburton79** [comment]
Situation has improved since 5c1e06605fabcf2631992f60f354be1004348729.
There are still multiple entries in certain cases, but the memory size is correct.

**Comment by jackburton79** [comment]
Fixed in 9cfb1148f2509185292885fe44be30ff08201648

**Comment by trentasis** [comment]
It works!
Thanks

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-10-31 15:03 GMT+01:00 Stefano Ceccherini <notifications@github.com>:
