### ISSUE TITLE
Install in thinstation 5.4

### ISSUE THREAD

**Issue by trentasis** [jackburton79/agent#7]
Hi,

I can't find any doc about how to install in thinstation 5.4, can you help?

- I have checked taht dmidecode doesn't exist i nthinstation, how are you obtaining info without dmidecode
- Can you detail steps to install in thinstaiton, in setup.sh appears THINSTATION_PATH  and SET_ENV, but I don't know where are this files

Config
THINSTATION_PATH=`cat ../../THINSTATION_PATH`

. ../SET_ENV

Thanks

**Comment by trentasis** [comment]
compiled with a x64 machine with some error (environm ent variables) and executing in thinstation appears:
line 1: syntax error: unexpected ")"

**Comment by jackburton79** [comment]
I haven't tried with Thinstation 5.4 yet. I guess they've changed something in the initialization scripts or in the build system.
For the missing dmidecode, yes, it's a problem. I can use lshw instead, but as far as I remember it's no longer available since Thinstation 5.
Where I work we still are on a mixed 2.2.2h and 5.2 ecosystem. I'll try the 5.4 version as soon as I have some time.

**Comment by trentasis** [comment]
Hi,

First of all thanks for your answer.
We are working with 2.2 and now are trying to upgrade to 5.4. It seems that
dmidecode now will be avaialbe in 5.4 master branch!
one, question, can you detail how to compile and install/configure on 2.2
version?

Thanks



2015-09-23 21:28 GMT+02:00 Stefano Ceccherini <notifications@github.com>:

**Comment by trentasis** [comment]
Hi can you send binary for 2.2 and instruction to install. We have tried to
compile manually and execute in 2.2 and error persist, same that appears in
5.4.
It will be great to has a binary and detail to compile install and
configure to inventory thinstation 2.2

Thanks

2015-09-23 23:26 GMT+02:00 Trenta sis <trenta.sis@gmail.com>:

**Comment by jackburton79** [comment]
Hi, did you already the binary from here ?
https://github.com/jackburton79/agent/releases


2015-09-24 11:23 GMT+02:00 trentasis <notifications@github.com>:

**Comment by trentasis** [comment]
Sorry, I don't know that binaries was located in this path.

I have tried with Thinstation 5.4 and now we can inventory with lshw and
without dmidecode, but only problem is memory is not inventoried
With lshw memory appears but seem that ocs agent can collect this info? How
can we solve?

Thanks


2015-09-24 12:41 GMT+02:00 Stefano Ceccherini <notifications@github.com>:

**Comment by trentasis** [comment]
memory in lshw appear that has 2GB but in inventory is showing 1616MB and
detail about dimm sizes are not showed, how can Iretrieve this information?

Thanks

2015-09-24 15:23 GMT+02:00 Trenta sis <trenta.sis@gmail.com>:

**Comment by trentasis** [comment]
very strange... with 5.4 seems to work (without memory dimm) but with 2.2
we receive an error:

./ocsinventory-agent: error while loading shared libraries: libstdc++.so.6:
cannot open shared object file: No such file or directory

You description was that with 2.2 was tested, how can I compile and
configure to work with this version?

Thanks


2015-09-24 15:34 GMT+02:00 Trenta sis <trenta.sis@gmail.com>:

**Comment by jackburton79** [comment]
I'm sure the agent works with Thinstation 2.2.2h or 2.2.2i.
Are you using one of these versions or something older ?

**Comment by trentasis** [comment]
finally work, it was a problem with dependency libs.

Thanks for all

**Comment by trentasis** [comment]
working perfect, thanks

2015-10-01 8:05 GMT+02:00 Stefano Ceccherini <notifications@github.com>:
