### ISSUE TITLE
date incorrect and inventory not updated correctly in some situations

### ISSUE THREAD

**Issue by trentasis** [jackburton79/agent#8]
in ocs agent appears that inventory date is incorrect and hits generates that inventory is not updated in some cases, always appear 2013-05-10-10-10 as inventory date

It seems that error is in Configuration.cpp and always appear :
 <DEVICEID>ts-2013-05-10-10-10-10</DEVICEID>
and generating local XML filename is the same  ts-2013-05-10-10-10-10.xml

If I import a modified xml with current date/time then it works... 

can you solve with current data/time and recompile?

Thanks

**Comment by trentasis** [comment]
Can you recompile with new patch and release a new version, I have recompiled but with local inventory work but my recompilation is not working with --server or -conf option

**Comment by jackburton79** [comment]
Hi,
I changed the device ID generation to use the system serial number or the MAC address of the first NIC.
The date used as the device ID has nothing to do with the inventory not updating, it's only needed by OCSInventoryNG Server as a part of the device ID.
